---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-deployment
spec:
  selector:
    matchLabels:
      app: covid19
  replicas: 1
  template:
    metadata:
      labels:
        app: covid19
    spec:
      containers:
      - name: covid19
        image: iad.ocir.io/bmcdw/covid19_python:latest
        imagePullPolicy: Always
        env:
        - name: RQ_DASHBOARD_USERNAME
          valueFrom:
            secretKeyRef:
              name: covid19-secrets
              key: RQ_DASHBOARD_USERNAME
        - name: RQ_DASHBOARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: covid19-secrets
              key: RQ_DASHBOARD_PASSWORD
        - name: CONTAINER_TYPE
          value: web
        - name: REDIS_HOST
          value: covid19-redis-service.default
        - name: APP_ENV
          value: prod
        - name: FLASK_APP
          value: app
      imagePullSecrets:
        - name: ocir-creds
---
  apiVersion: v1
  kind: Service
  metadata:
    name: covid19-service
    labels:
      app: covid19
  spec:
    type: LoadBalancer
    ports:
      - name: web
        port: 80
        protocol: TCP
        targetPort: 5000
    selector:
      app: covid19
