---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: covid19-redis-deployment
spec:
  selector:
    matchLabels:
      app: covid19-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: covid19-redis
    spec:
      containers:
      - name: covid19-redis
        image: redis:6.0.1-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: covid19-redis-service
  labels:
    app: covid19-redis
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: covid19-redis