---
apiVersion: v1
kind: Service
metadata:
  name: covid19-service
  labels:
    app: covid19
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: covid19