version: '3.7'

services:

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/covid19
    ports:
      - target: 5000
        published: 5000
    environment:
      CONTAINER_TYPE: web
    env_file:
      - devops/common.env
      - devops/secrets.env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/covid19
    environment:
      CONTAINER_TYPE: worker
    env_file:
      - devops/common.env

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/covid19
    environment:
      CONTAINER_TYPE: scheduler
    env_file:
      - devops/common.env
      
  redis:
    image: redis:5.0.8-alpine
    #image: redislabs/redisjson2:latest
    expose:
      - 6379
    ports:
      - target: 6379
        published: 6379
  